ARG NODE_VERSION=24-alpine
FROM node:$NODE_VERSION AS base
ARG PG_URL
ARG PNPM_VERSION=10.11.0

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NODE_ENV=production
ENV PG_URL=postgres

RUN npm install --global corepack@latest && \
    corepack enable && \
    corepack prepare pnpm@${PNPM_VERSION} --activate

FROM base AS deps

WORKDIR /app

COPY --chown=node:node package*.json pnpm* ./
COPY --chown=node:node ./workers/stats-aggregate-worker/package.json workers/stats-aggregate-worker/
COPY --chown=node:node ./packages/common/package.json packages/common/
COPY --chown=node:node ./packages/infra/package.json packages/infra/
COPY --chown=node:node ./packages/services/package.json packages/services/
COPY --chown=node:node ./db/package.json db/

RUN pnpm install --frozen-lockfile

FROM deps AS builder

COPY --chown=node:node ./workers/stats-aggregate-worker workers/stats-aggregate-worker
COPY --chown=node:node ./packages/common packages/common
COPY --chown=node:node ./packages/infra packages/infra
COPY --chown=node:node ./packages/services packages/services
COPY --chown=node:node ./db db

RUN pnpm --filter @urlshortener/db generate
RUN pnpm --filter @urlshortener/db build
RUN pnpm --filter @urlshortener/common build
RUN pnpm --filter @urlshortener/infra build
RUN pnpm --filter @urlshortener/services build
RUN pnpm --filter @urlshortener/stats-aggregate-worker build

FROM base AS server

USER node
WORKDIR /app

COPY --from=deps --chown=node:node /app/node_modules ./node_modules
COPY --from=deps --chown=node:node /app/package*.json ./
COPY --from=deps --chown=node:node /app/pnpm* ./

COPY --from=builder --chown=node:node /app/workers/stats-aggregate-worker workers/stats-aggregate-worker
COPY --from=builder --chown=node:node /app/packages/common packages/common
COPY --from=builder --chown=node:node /app/packages/infra packages/infra
COPY --from=builder --chown=node:node /app/packages/services packages/services
COPY --from=builder --chown=node:node /app/db db

CMD ["node", "workers/stats-aggregate-worker/dist/index.js"]
