ARG NODE_VERSION=24-alpine
FROM node:$NODE_VERSION AS base
ARG PG_URL

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV NODE_ENV=production
ENV PG_URL=$PG_URL

RUN npm install --global corepack@latest && \
    corepack enable pnpm
FROM base AS deps

WORKDIR /app

COPY --chown=node:node package*.json pnpm* ./
COPY --chown=node:node ./apps/backend/package.json apps/backend/
COPY --chown=node:node ./db/package.json db/

RUN pnpm install --frozen-lockfile

FROM deps AS builder

COPY --chown=node:node ./apps/backend apps/backend
COPY --chown=node:node ./db db/

RUN pnpm --filter @urlshortener/db generate
RUN pnpm --filter @urlshortener/db build
RUN pnpm --filter @urlshortener/backend build

# Stage final
FROM base AS server

USER node
WORKDIR /app

COPY --from=deps --chown=node:node /app/node_modules ./node_modules
COPY --from=deps --chown=node:node /app/package*.json ./
COPY --from=deps --chown=node:node /app/pnpm* ./

COPY --from=builder --chown=node:node /app/apps/backend apps/backend
COPY --from=builder --chown=node:node /app/db db/
COPY --chown=node:node /scripts /app/scripts

RUN chmod +x /app/scripts/backend.entrypoint.sh
RUN chmod +x /app/scripts/worker.entrypoint.sh

ENTRYPOINT ["/app/scripts/backend.entrypoint.sh"]
