/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateShortenurlRouteImport } from './routes/createShortenurl'
import { Route as IndexRouteImport } from './routes/index'

const CreateShortenurlRoute = CreateShortenurlRouteImport.update({
  id: '/createShortenurl',
  path: '/createShortenurl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createShortenurl': typeof CreateShortenurlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createShortenurl': typeof CreateShortenurlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/createShortenurl': typeof CreateShortenurlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createShortenurl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createShortenurl'
  id: '__root__' | '/' | '/createShortenurl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateShortenurlRoute: typeof CreateShortenurlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/createShortenurl': {
      id: '/createShortenurl'
      path: '/createShortenurl'
      fullPath: '/createShortenurl'
      preLoaderRoute: typeof CreateShortenurlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateShortenurlRoute: CreateShortenurlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
